title: Next-Gen Sequencing tools from the Horvath Lab
theme: jekyll-theme-slate

defaults:
  -
    scope:
      path: "SCReadCounts"
      type: "pages"
    values:
      layout: "screadcounts"
  -
    scope:
      path: "SCExecute"
      type: "pages"
    values:
      layout: "scexecute"
